<a href="https://colab.research.google.com/github/lakshay-batra712/Lakshay_Batra_102303743_UML501/blob/main/ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Q1 A

In [ ]:
arr =np.array([1,2,3,6,4,5])
arr= np.flip(arr)
arr

array([5, 4, 6, 3, 2, 1])

# Q1 B

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatarr=array1.flatten()
print(flatarr)

flat2arr=array1.ravel()
print(flat2arr)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


# Q1 C

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

np.array_equal(arr1,arr2)

True

# Q1 D (i)

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique, counts = np.unique(x, return_counts=True)
most_frequent = unique[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print(most_frequent)
print(indices)

1
[0 5 7 8 9]


# Q1 D (ii)

In [ ]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3 ])
unique, counts = np.unique(x, return_counts=True)
most_frequent = unique[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print(most_frequent)
print(indices)

1
[0 1 2]


# Q1 E (i)

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum=np.sum(gfg)
print(sum)

45


# Q1 E (ii)

In [ ]:
rowsum=np.sum(gfg,axis=1)
print(rowsum)

[[14]
 [16]
 [15]]


# Q1 E (iii)

In [ ]:
colsum=np.sum(gfg,axis=0)
print(colsum)

[[20  9 16]]


# Q1 F(i)

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diagsum=np.trace(n_array)
print(diagsum)

176


# Q1 F (ii)

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(eigenvalues)


[98.16835147 28.097044   49.73460452]


# Q1 F (iii)

In [ ]:
print(eigenvectors)

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


# Q1 F (iv)

In [ ]:
n_array_inv=np.linalg.inv(n_array)
print(n_array_inv)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


# Q1 F (v)

In [ ]:
n_array_det=np.linalg.det(n_array)
print(n_array_det)

137180.0000000001


# Q1 G (i)

In [ ]:
p = np.array([[1, 2], [2, 3]])
q=np.array( [[4, 5], [6, 7]] )
p_flat = p.flatten()
q_flat = q.flatten()
cov_matrix = np.cov(p_flat,q_flat)
print("Covarience:")
print(cov_matrix)

multiplied=p@q
print("\n Multiplication:")
print(multiplied)

Covarience:
[[0.66666667 1.        ]
 [1.         1.66666667]]

 Multiplication:
[[16 19]
 [26 31]]


# Q1 G (ii)

In [ ]:
p = np.array([[1, 2], [2, 3], [4, 5]] )
q = np.array([[4, 5, 1], [6, 7, 2]] )
p_flat = p.flatten()
q_flat = q.flatten()
cov_matrix2 = np.cov(p_flat,q_flat)
print("Covarience:")
print(cov_matrix2)

multiplied2=p@q
print("\n Multiplication:")
print(multiplied2)

Covarience:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]

 Multiplication:
[[16 19  5]
 [26 31  8]
 [46 55 14]]


# Q1 H

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.dot(x.flatten(), y.flatten())
print ("Inner Product: ")
print(inner_product)

outer_product = np.outer(x.flatten(), y.flatten())
print("Outer Product:")
print(outer_product)

x_flat = x.flatten()
y_flat = y.flatten()
x_repeated = np.repeat(x_flat, len(y_flat))
y_tiled = np.tile(y_flat, len(x_flat))

cartesian_prod = np.column_stack([x_repeated, y_tiled])
print("Cartisian Product: ")
print(cartesian_prod)


Inner Product: 
79
Outer Product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartisian Product: 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# Q2(a)(i)

In [ ]:
array = np.array([[1,-2,3],[-4,5,-6]])
absolute_array = np.absolute(array)
print(absolute_array)

[[1 2 3]
 [4 5 6]]


# Q2 A (ii)

In [ ]:
flat = array.flatten()
p_flat = np.percentile(flat, [25, 50, 75])
print("Percentiles (flattened):", p_flat)
p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles (each column):\n", p_col)
p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles (each row):\n", p_row)



Percentiles (flattened): [-3.5 -0.5  2.5]
Percentiles (each column):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (each row):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


# Q2 (a)(iii)

In [ ]:
mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print("Flattened -> ")
print ("Mean:",mean_flat, "Median:", median_flat, "Std Dev:", std_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Column-wise -> ")
print("Mean:",mean_col, "Median:", median_col, "Std Dev:", std_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Row-wise -> ")
print("Mean:" ,mean_row, "Median:", median_row, "Std Dev:", std_row)


Flattened -> 
Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224
Column-wise -> 
Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std Dev: [2.5 3.5 4.5]
Row-wise -> 
Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std Dev: [2.05480467 4.78423336]


# Q2 (b)

In [ ]:
a=np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
print( "floor:",floor)
ceil = np.ceil(a)
print("ceiling:", ceil)
trunc=np.trunc(a)
print("truncated:", trunc)
rounded=np.round(a)
print("Rounded:", rounded)


floor: [-2. -2. -1.  0.  1.  1.  3.]
ceiling: [-1. -1. -0.  1.  2.  2.  3.]
truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


# Q3 A (i)

In [ ]:
array=np.array([10, 52, 62, 16, 16, 54, 453])
sorted_arr=np.sort(array)
print(sorted_arr)

[ 10  16  16  52  54  62 453]


# Q3 A (ii)

In [ ]:
sort_indices=np.argsort(array)
print(sort_indices)

[0 3 4 1 5 2 6]


# Q3 A (iii)

In [ ]:
smallest_4=sorted_arr[:4]
print(smallest_4)

[10 16 16 52]


# Q3 A (iv)

In [ ]:
largest_5=sorted_arr[-5:]
print(largest_5)

[ 16  52  54  62 453]


# Q3 B

In [ ]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
integer_elements = array[array == np.floor(array)]
print("Integer elements:",integer_elements)
float_elements = array[array != np.floor(array)]
print("Float elements:",float_elements)

Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


# Q4

In [ ]:
from google.colab import files
uploaded = files.upload()



KeyboardInterrupt



In [ ]:
from PIL import Image, ImageFile
import numpy as np

ImageFile.LOAD_TRUNCATED_IMAGES = True

def img_to_array(path):
    try:
        img = Image.open(path)
        img_arr = np.array(img)

        if img_arr.ndim == 2:
            print("Grayscale image detected")
            np.savetxt("image_grayscale.txt", img_arr, fmt='%d')
            return "grayscale"

        elif img_arr.ndim == 3:
            print("RGB image detected")
            flat = img_arr.reshape(-1, img_arr.shape[2])
            np.savetxt("image_rgb.txt", flat, fmt='%d')
            return "rgb"

        else:
            print("Image format not recognized")
            return None

    except Exception as e:
        print("Error:", e)
        return None

image_type = img_to_array("scorpio.jpeg")

if image_type == "grayscale":
    gray = np.loadtxt("image_grayscale.txt", dtype=int)
    print("Loaded grayscale shape:", gray.shape)
    print(gray[:5])

elif image_type == "rgb":
    rgb = np.loadtxt("image_rgb.txt", dtype=int)
    print("Loaded RGB shape:", rgb.shape)
    print(rgb[:5])
else:
    print("Could not load the saved image data.")

RGB image detected
Loaded RGB shape: (50232, 3)
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
